# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Letisia's Technology Portfolio"
title_separator: "|"
email: contact@letisiapangataa.com
description: "Official Technology Portfolio by Letisia Pangata'a. Ko hoku hingoa ko Letisia. Ko Letisia tōku ingoa. My name is Letisia. Student of computers with a passion for creative arts, business and entrepreneurship, to science and technology. Inspired by my interests and Tongan heritage, focused on providing creative insight and discipline in science into personal and professional projects. Mālō aupito’ from Aotearoa, New Zealand."
url: "https://letisiapangataa.github.io"
repository: "letisiapangataa/letisiapangataa.github.io"
masthead_title: "Letisia's Technology Portfolio"
twitter_username: letisiapangataa
github_username: letisiapangataa
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata

author:
  # name   : "Letisia Pangata'a"
  # avatar : "https://res.cloudinary.com/louiy9obu/image/upload/v1628419918/B84D1E9F-0C77-4FE3-9AEE-A7EAC0BCB8D9_evlxba.jpg"
  bio    : ""
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw"
      url: "https://www.linkedin.com/in/letisiapangataa/"
    - label: "Github"
      icon: "fab fa-fw"
      url: "https://github.com/letisiapangataa"
    - label: "YouTube"
      icon: "fab fa-fw"
      url: "https://www.youtube.com/channel/UCnWTpRSfYSxAWmCRUpl4PBQ/featured"
    - label: "HackerRank"
      icon: "fab fa-fw"
      url: "https://www.hackerrank.com/letisiapangataa?hr_r=1"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw"
      url: "https://www.linkedin.com/in/letisiapangataa/"
    - label: "Github"
      icon: "fab fa-fw"
      url: "https://github.com/letisiapangataa"
    - label: "YouTube"
      icon: "fab fa-fw"
      url: "https://www.youtube.com/channel/UCnWTpRSfYSxAWmCRUpl4PBQ/featured"
    - label: "HackerRank"
      icon: "fab fa-fw"
      url: "https://www.hackerrank.com/letisiapangataa?hr_r=1"

teaser: /assets/images/500x300.png


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
